server:
  port: 80

spring:
  application:
    name: api-gateway

services:
  url:
    user_service: http://localhost:8080
    auth_service: http://localhost:8081
    order_service: http://localhost:8082