spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false

security:
  jwt-key: ${JWT_KEY}

server:
  port: 80

eureka:
  client:
    webclient:
      enabled: false