spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false

security:
  jwt-key: ${JWT_KEY}

server:
  port: 80

eureka:
  client:
    webclient:
      enabled: false

services:
  urls:
    user-service: ${USER_SERVICE_URL}
    auth-service: ${AUTH_SERVICE_URL}
    order-service: ${ORDER_SERVICE_URL}
    payment-service: ${PAYMENT_SERVICE_URL}
    camunda: ${CAMUNDA_URL}

front-end:
  url: ${FRONT_END_URL:http://localhost:3000}